### ISSUE TITLE
Linear Filters with alssms

### ISSUE THREAD

**Issue by retowildhaber** [lmlib/lmlib#21]
Linear Filters should write as:

costs = lm.CompositeCost(alssms, (segment_left, segment_right), F=np.ones( (M, 2) ))

# filter signal and take the approximation
rls = lm.create_rls(costs, steady_state=True)
y_hat = rls.filter_minimize_y(y, c0)  # naming must be discussed; alternative: rls.alssm_filter(y, c0)

**Comment by fwaldmann** [comment]
y_hats =  rls.filter_minimize_yhat(y, c0=None)

statespce applciations:
alssm_filt(y, alssms, segments)

**Comment by fwaldmann** [comment]
Example Structre

Version 1
---------
costs.eval_alssm_output()

Version 2
---------
y_hats = rls.filter_minimize_yhat(y, c0=None)

Version 3
---------
alssm_filt(y, alssms, segments)

**Comment by fwaldmann** [comment]
commit on 21-linear-filters-with-alssms

**Comment by fwaldmann** [comment]
fix v2.1.2 #46
