### ISSUE TITLE
as_2dim_C is not documented

### ISSUE THREAD

**Issue by retowildhaber** [lmlib/lmlib#36]
In the doc of ALSSM the parameter as_2dim_C appears. However, it is not documented how to be used.

**Comment by fwaldmann** [comment]
Old documentation. 

Function needs to be rewritten and documented.

**Comment by fwaldmann** [comment]
force_2d_C

**Comment by fwaldmann** [comment]
force_C_2d
force_2D
force2D
MC_input
force_MC <---
forceMC

**Comment by fwaldmann** [comment]
fix v2.1.2 #46
