### ISSUE TITLE
Interface modifications for lmlib.utils.generator.gen_rect(K, k_period, k_on)

### ISSUE THREAD

**Issue by retowildhaber** [lmlib/lmlib#6]
The current interface of lmlib.utils.generator.gen_rect(K, k_period, k_on) could be improved. 

Proposal:
lmlib.utils.generator.gen_rect(K, k_period, k_on = k_period//2, duty_cycle = 0.5, k0)

with 
 - k_on = k_phase//2 as default value
 - k0 = signal is shifted such that at k0 the signal changes from 0 to 1. (cf. gen_sine)
 - duty_cycle = 0.0 to 1.0.  Sets the ratio (k_on/k_period). Only one of the two parameters k_on and duty_cycle can be set at the same time. An error is thrown otherwise.

**Comment by fwaldmann** [comment]
added feature to https://github.com/lmlib/lmlib/tree/dev branch

**Comment by fwaldmann** [comment]
Fixed in release v2.1.0
rev. 841cf96ec478daacf2fdbf03f14607f5151ec5ec
